"""initial

Revision ID: c5c1cb5b9c96
Revises: 
Create Date: 2025-10-06 16:34:14.622407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5c1cb5b9c96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_gateways',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('gateway_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('gateway_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('gateway_type', sa.Enum('MIDTRANS', 'XENDIT', 'DOKU', 'NICEPAY', 'FASPAY', name='gatewaytype'), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_sandbox', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('supported_methods', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_gateways_gateway_code'), 'payment_gateways', ['gateway_code'], unique=True)
    op.create_table('payment_methods',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('method_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('method_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('method_type', sa.Enum('VIRTUAL_ACCOUNT', 'E_WALLET', 'CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER', 'QRIS', 'RETAIL', name='methodtype'), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('icon_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('admin_fee', sa.Float(), nullable=False),
    sa.Column('admin_fee_type', sa.Enum('FIXED', 'PERCENTAGE', name='adminfeetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_method_code'), 'payment_methods', ['method_code'], unique=True)
    op.create_table('product_categories',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vouchers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('application_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('voucher_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('voucher_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('voucher_type', sa.Enum('PUBLIC', 'PRIVATE', 'REFERRAL', 'CASHBACK', name='vouchertype'), nullable=False),
    sa.Column('discount_type', sa.Enum('FIXED', 'PERCENTAGE', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('max_discount', sa.Float(), nullable=True),
    sa.Column('min_transaction', sa.Float(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('usage_limit_per_user', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_auto_apply', sa.Boolean(), nullable=False),
    sa.Column('applicable_products', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vouchers_application_id'), 'vouchers', ['application_id'], unique=False)
    op.create_index(op.f('ix_vouchers_voucher_code'), 'vouchers', ['voucher_code'], unique=True)
    op.create_table('payment_gateway_credentials',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('application_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('gateway_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('merchant_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('api_secret', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('client_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('webhook_secret', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('additional_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gateway_id'], ['payment_gateways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_gateway_credentials_application_id'), 'payment_gateway_credentials', ['application_id'], unique=False)
    op.create_index(op.f('ix_payment_gateway_credentials_gateway_id'), 'payment_gateway_credentials', ['gateway_id'], unique=False)
    op.create_table('payment_method_gateways',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('payment_method_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('gateway_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('gateway_method_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('processing_time_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gateway_id'], ['payment_gateways.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_method_gateways_gateway_id'), 'payment_method_gateways', ['gateway_id'], unique=False)
    op.create_index(op.f('ix_payment_method_gateways_payment_method_id'), 'payment_method_gateways', ['payment_method_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('application_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('category_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('product_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('product_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_application_id'), 'products', ['application_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('application_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('transaction_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('payment_method_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('gateway_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('voucher_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'AWAITING_PAYMENT', 'PAID', 'SETTLEMENT', 'EXPIRED', 'CANCELLED', 'FAILED', 'REFUNDED', name='transactionstatus'), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('admin_fee', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('payment_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('payment_token', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('va_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('qr_code_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gateway_id'], ['payment_gateways.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_application_id'), 'transactions', ['application_id'], unique=False)
    op.create_index(op.f('ix_transactions_gateway_id'), 'transactions', ['gateway_id'], unique=False)
    op.create_index(op.f('ix_transactions_invoice_number'), 'transactions', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_transactions_payment_method_id'), 'transactions', ['payment_method_id'], unique=False)
    op.create_index(op.f('ix_transactions_payment_reference'), 'transactions', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_code'), 'transactions', ['transaction_code'], unique=True)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_transactions_voucher_id'), 'transactions', ['voucher_id'], unique=False)
    op.create_table('voucher_conditions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('voucher_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('condition_type', sa.Enum('MIN_AMOUNT', 'MAX_AMOUNT', 'PRODUCT_ID', 'CATEGORY_ID', 'USER_SEGMENT', 'PAYMENT_METHOD', name='conditiontype'), nullable=False),
    sa.Column('operator', sa.Enum('EQUAL', 'NOT_EQUAL', 'GREATER_THAN', 'LESS_THAN', 'IN', 'NOT_IN', name='operatortype'), nullable=False),
    sa.Column('condition_value', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_conditions_voucher_id'), 'voucher_conditions', ['voucher_id'], unique=False)
    op.create_table('voucher_eligible_users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('voucher_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('application_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('eligible_at', sa.DateTime(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_claimed', sa.Boolean(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_eligible_users_application_id'), 'voucher_eligible_users', ['application_id'], unique=False)
    op.create_index(op.f('ix_voucher_eligible_users_user_id'), 'voucher_eligible_users', ['user_id'], unique=False)
    op.create_index(op.f('ix_voucher_eligible_users_voucher_id'), 'voucher_eligible_users', ['voucher_id'], unique=False)
    op.create_table('payment_gateway_callbacks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('gateway_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('callback_type', sa.Enum('PAYMENT_NOTIFICATION', 'TRANSACTION_STATUS', 'REFUND_NOTIFICATION', name='callbacktype'), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('signature', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_signature_valid', sa.Boolean(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gateway_id'], ['payment_gateways.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_gateway_callbacks_gateway_id'), 'payment_gateway_callbacks', ['gateway_id'], unique=False)
    op.create_index(op.f('ix_payment_gateway_callbacks_is_processed'), 'payment_gateway_callbacks', ['is_processed'], unique=False)
    op.create_index(op.f('ix_payment_gateway_callbacks_transaction_id'), 'payment_gateway_callbacks', ['transaction_id'], unique=False)
    op.create_table('payment_gateway_requests',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('gateway_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('request_type', sa.Enum('CREATE_PAYMENT', 'CHECK_STATUS', 'CANCEL_PAYMENT', 'REFUND', name='requesttype'), nullable=False),
    sa.Column('request_method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('request_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gateway_id'], ['payment_gateways.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_gateway_requests_gateway_id'), 'payment_gateway_requests', ['gateway_id'], unique=False)
    op.create_index(op.f('ix_payment_gateway_requests_idempotency_key'), 'payment_gateway_requests', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_payment_gateway_requests_transaction_id'), 'payment_gateway_requests', ['transaction_id'], unique=False)
    op.create_table('transaction_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('product_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('item_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_items_product_id'), 'transaction_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_transaction_items_transaction_id'), 'transaction_items', ['transaction_id'], unique=False)
    op.create_table('voucher_usage',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('voucher_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('application_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_usage_application_id'), 'voucher_usage', ['application_id'], unique=False)
    op.create_index(op.f('ix_voucher_usage_transaction_id'), 'voucher_usage', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_voucher_usage_user_id'), 'voucher_usage', ['user_id'], unique=False)
    op.create_index(op.f('ix_voucher_usage_voucher_id'), 'voucher_usage', ['voucher_id'], unique=False)
    op.create_table('transaction_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('previous_status', sa.Enum('PENDING', 'AWAITING_PAYMENT', 'PAID', 'SETTLEMENT', 'EXPIRED', 'CANCELLED', 'FAILED', 'REFUNDED', name='transactionstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('PENDING', 'AWAITING_PAYMENT', 'PAID', 'SETTLEMENT', 'EXPIRED', 'CANCELLED', 'FAILED', 'REFUNDED', name='transactionstatus'), nullable=False),
    sa.Column('changed_by', sa.Enum('SYSTEM', 'USER', 'GATEWAY', 'ADMIN', name='changedby'), nullable=False),
    sa.Column('gateway_callback_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gateway_callback_id'], ['payment_gateway_callbacks.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_logs_transaction_id'), 'transaction_logs', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_logs_transaction_id'), table_name='transaction_logs')
    op.drop_table('transaction_logs')
    op.drop_index(op.f('ix_voucher_usage_voucher_id'), table_name='voucher_usage')
    op.drop_index(op.f('ix_voucher_usage_user_id'), table_name='voucher_usage')
    op.drop_index(op.f('ix_voucher_usage_transaction_id'), table_name='voucher_usage')
    op.drop_index(op.f('ix_voucher_usage_application_id'), table_name='voucher_usage')
    op.drop_table('voucher_usage')
    op.drop_index(op.f('ix_transaction_items_transaction_id'), table_name='transaction_items')
    op.drop_index(op.f('ix_transaction_items_product_id'), table_name='transaction_items')
    op.drop_table('transaction_items')
    op.drop_index(op.f('ix_payment_gateway_requests_transaction_id'), table_name='payment_gateway_requests')
    op.drop_index(op.f('ix_payment_gateway_requests_idempotency_key'), table_name='payment_gateway_requests')
    op.drop_index(op.f('ix_payment_gateway_requests_gateway_id'), table_name='payment_gateway_requests')
    op.drop_table('payment_gateway_requests')
    op.drop_index(op.f('ix_payment_gateway_callbacks_transaction_id'), table_name='payment_gateway_callbacks')
    op.drop_index(op.f('ix_payment_gateway_callbacks_is_processed'), table_name='payment_gateway_callbacks')
    op.drop_index(op.f('ix_payment_gateway_callbacks_gateway_id'), table_name='payment_gateway_callbacks')
    op.drop_table('payment_gateway_callbacks')
    op.drop_index(op.f('ix_voucher_eligible_users_voucher_id'), table_name='voucher_eligible_users')
    op.drop_index(op.f('ix_voucher_eligible_users_user_id'), table_name='voucher_eligible_users')
    op.drop_index(op.f('ix_voucher_eligible_users_application_id'), table_name='voucher_eligible_users')
    op.drop_table('voucher_eligible_users')
    op.drop_index(op.f('ix_voucher_conditions_voucher_id'), table_name='voucher_conditions')
    op.drop_table('voucher_conditions')
    op.drop_index(op.f('ix_transactions_voucher_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_code'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_method_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_invoice_number'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_gateway_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_application_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_application_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_payment_method_gateways_payment_method_id'), table_name='payment_method_gateways')
    op.drop_index(op.f('ix_payment_method_gateways_gateway_id'), table_name='payment_method_gateways')
    op.drop_table('payment_method_gateways')
    op.drop_index(op.f('ix_payment_gateway_credentials_gateway_id'), table_name='payment_gateway_credentials')
    op.drop_index(op.f('ix_payment_gateway_credentials_application_id'), table_name='payment_gateway_credentials')
    op.drop_table('payment_gateway_credentials')
    op.drop_index(op.f('ix_vouchers_voucher_code'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_application_id'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_payment_methods_method_code'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_payment_gateways_gateway_code'), table_name='payment_gateways')
    op.drop_table('payment_gateways')
    # ### end Alembic commands ###
